# Generated by Django 2.2.28 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_last_counter',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
