# Generated by Django 2.2.28 on 2026-07-23

from django.db import migrations, models


def enable_bound_authenticators(apps, schema_editor):
    user_model = apps.get_model('account', 'User')
    user_model.objects.exclude(mfa_secret__isnull=True).exclude(
        mfa_secret=''
    ).update(mfa_enabled=True)


def disable_account_mfa(apps, schema_editor):
    user_model = apps.get_model('account', 'User')
    user_model.objects.update(mfa_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_totp_mfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            enable_bound_authenticators,
            disable_account_mfa,
        ),
    ]
