# Generated by Django 2.2.28 on 2026-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_deployrequest_failed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployiteration',
            name='status',
            field=models.CharField(choices=[('0', '待发布'), ('1', '发布中'), ('2', '发布成功'), ('-1', '部分失败'), ('-3', '发布失败')], default='0', max_length=2),
        ),
    ]
